-- AlterTable
ALTER TABLE `user` ADD COLUMN `city` VARCHAR(191) NULL,
    ADD COLUMN `company_address` VARCHAR(191) NULL,
    ADD COLUMN `company_city` VARCHAR(191) NULL,
    ADD COLUMN `company_country` VARCHAR(191) NULL,
    ADD COLUMN `company_email` VARCHAR(191) NULL,
    ADD COLUMN `company_first_name` VARCHAR(191) NULL,
    ADD COLUMN `company_last_name` VARCHAR(191) NULL,
    ADD COLUMN `company_logo` VARCHAR(191) NULL,
    ADD COLUMN `company_phone` VARCHAR(191) NULL,
    ADD COLUMN `country` VARCHAR(191) NULL,
    ADD COLUMN `description` LONGTEXT NULL,
    ADD COLUMN `facebook_url` VARCHAR(191) NULL,
    ADD COLUMN `google_map` LONGTEXT NULL,
    ADD COLUMN `instagram_url` VARCHAR(191) NULL,
    ADD COLUMN `is_agree` INTEGER NULL DEFAULT 1,
    ADD COLUMN `is_approve` INTEGER NULL,
    ADD COLUMN `postal_code` VARCHAR(191) NULL,
    ADD COLUMN `tax_id` VARCHAR(191) NULL,
    ADD COLUMN `twitter_url` VARCHAR(191) NULL,
    ADD COLUMN `website_url` VARCHAR(191) NULL,
    ADD COLUMN `youtube_url` VARCHAR(191) NULL;
